# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BgtLoader
                                 A QGIS plugin
 Plugin downloads and imports the BGT from API.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-08
        copyright            : (C) 2024 by Max van der Waal
        email                : m.vanderwaal@tudelft.nl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Max van der Waal'
__date__ = '2024-10-08'
__copyright__ = '(C) 2024 by Max van der Waal'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BgtLoader class from file BgtLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .bgt_loader import BgtLoaderPlugin
    return BgtLoaderPlugin()
